name: CI

on:
  pull_request:
    branches:
    - main
  merge_group:
jobs:
  lint_with_ruff:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory: ["./type-enum", "./type-enum-plugin"]

    defaults:
      run:
        working-directory: ${{ matrix.directory }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    - name: Lint with ruff
      run: |
        ruff check --output-format=github type_enum*
    - name: Format with ruff
      run: |
        ruff format --check type_enum*


  run_tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./type-enum

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          poetry env use 3.11
          poetry install --no-interaction --no-root
      - name: Run tests
        run: |
          poetry run python -m unittest -v

  type_check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./type-enum

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          poetry env use 3.11
          poetry install --no-interaction --no-root
      - name: Run type check
        run: |
          poetry run mypy tests
