name: CI

on:
  pull_request:
    branches:
    - main
  merge_group:
jobs:
  format_with_black:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install black
      run: |
        python -m pip install --upgrade pip
        pip install 'black<=23'
    - name: Format with black
      run: |
        python -m black --check -t py310 type_enum/
        python -m black --check -t py310 tests/

  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Install dependencies
        run: |
          # keep the following in sync with `test_with_pytest`!
          poetry env use 3.10
          poetry install --no-interaction --no-root
      - name: Run tests
        run: |
          poetry run python -m pytest -vv tests
