name: CI

on:
  pull_request:
    branches:
    - main
  merge_group:

jobs:
  lint_with_ruff:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory: ["./type-enum", "./type-enum-plugin"]

    defaults:
      run:
        working-directory: ${{ matrix.directory }}

    steps:
      - uses: actions/checkout@v3
      - name: Install rye
        uses: eifinger/setup-rye@v1
      - name: Lint with ruff
        run: |
          rye lint -- --output-format=github
      - name: Format with ruff
        run: |
          rye fmt -- --diff type_enum*

  run_tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./type-enum

    steps:
      - uses: actions/checkout@v3
      - name: Install rye
        uses: eifinger/setup-rye@v1

      - name: Install dependencies
        run: |
          rye sync --no-lock
      - name: Run tests
        run: |
          rye run test -v

  type_check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./type-enum

    steps:
      - uses: actions/checkout@v3
      - name: Install rye
        uses: eifinger/setup-rye@v1

      - name: Install dependencies
        run: |
          rye sync --no-lock
      - name: Run type check
        run: |
          rye run mypy
